[web]
port = 9090
username = "admin"
password = "admin"

[commands_api]
port = 9099

[[accounts]]
name = "default"
username = "2001"
password = "20+Sopho-07"
server = "172.16.50.11:5060"
domain = "172.16.50.11"
sip_port = 5060
rtp_port_start = 8000
rtp_port_end = 8010
auth_method = "md5"
codec = "pcmu"
transport = "udp"
register_expiry = 3600
register_retry_interval = 30
early_media = true
session_timers = false
auto_answer = false
ivr_timeout = 10
